services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: whisper
      POSTGRES_PASSWORD: druva150

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

  redis:
    image: redis:8.0-M03-alpine
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
    volumes:
      - 'redis_data:/var/lib/redis'

  redis-commander:
    container_name: redis-commander-whisper
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    ports:
      - '8081:8081'
volumes:
  pgdata:
  redis_data:
