export const ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET';
export const ACCESS_TOKEN_EXPIRY = 'ACCESS_TOKEN_EXPIRY';

export const REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET';
export const REFRESH_TOKEN_EXPIRY = 'REFRESH_TOKEN_EXPIRY';

export const ONBOARDING_TOKEN_SECRET = 'ONBOARDING_TOKEN_SECRET';
export const ONBOARDING_TOKEN_EXPIRY = 'ONBOARDING_TOKEN_EXPIRY';
